site_url: http://lab.carcinize.com
site_name: VMWare Training
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.inlinehilite
extra_css:
  - stylesheets/extra.css
  - stylesheets/admon.css
theme:
  logo: /img/vmware_logo.png
  name: material
  font:
    text: Roboto
  palette:
    scheme: default
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tracking
plugins:
  - search
  - mkdocs-video
nav:
  - Kubernetes:
     - Introduction: index.md
     - 1. Kubernetes Pods: pods.md
     - 2. Pod Networking: networking.md
     - 3. Service Networking: service-networking.md
  - Advanced:
     - 1. Network Plugins: plugins.md
  - Contact:
     - Contact Us: contact.md
